# Copyright 2022 Heath Stewart.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.

name: release

on:
  push:
    tags:
    - "v*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  GOVERSION: "1.19"

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    with:
      release: true

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    # Check out with full history to generate release notes.
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Release
      run: gh release create ${{ github.ref_name }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: cli/gh-extension-precompile@v1
      with:
        go_version: ${{ env.GOVERSION }}
